event_inherited()
scr_guiLayoutOffsetUpdate(o_skill_bw_resurrection_ico, 138, 118, 1)
scr_guiLayoutOffsetUpdate(o_skill_bw_touch_ico, 81, 171, 1)
scr_guiLayoutOffsetUpdate(o_pass_skill_nmadness, 100, 118, 1)
scr_guiLayoutOffsetUpdate(o_pass_skill_ndarkness, 62, 118, 1)
scr_guiLayoutOffsetUpdate(o_skill_soul_explosion_ico, 138, 171, 1)
scr_guiLayoutOffsetUpdate(o_pass_skill_imortall, 24, 221, 1)
scr_guiLayoutOffsetUpdate(o_pass_skill_kingdead, 100, 221, 1)
scr_guiLayoutOffsetUpdate(o_skill_Lostsouls_ico, 62, 221, 1)
scr_guiLayoutOffsetUpdate(o_skill_bw_wraithsummon_ico, 138, 221, 1)
scr_guiLayoutOffsetUpdate(o_bw_curse_ico, 130, 55, 1)
scr_guiLayoutOffsetUpdate(o_skill_death_plague_ico, 81, 55, 1)
scr_guiLayoutOffsetUpdate(o_bw_darkbolt_ico, 33, 55, 1)
scr_guiLayoutOffsetUpdate(o_bw_dark_bless_ico, 24, 118, 1)
scr_guiLayoutOffsetUpdate(o_pass_skill_unholymind, 24, 171, 1)
