with (target)
{
    if (object_index == o_harpy)
        scr_enemy_change_form(s_harpy_undead)
    if (object_index == o_wolf)
        scr_enemy_change_form(s_wolf_undead)
    if (object_index == o_moose)
        scr_enemy_change_form(s_moose_undead)
    if (object_index == o_bear)
        scr_enemy_change_form(s_bear_undead)
    if (object_index == o_bison)
        scr_enemy_change_form(s_bison_undead)
    if (object_index == o_gulon)
        scr_enemy_change_form(s_golun_undead)
    if (object_index == o_boar)
        scr_enemy_change_form(s_boar_undead)
    if (object_index == o_crawler)
        scr_enemy_change_form(s_crawler_undead)
}
