ds_map_replace(data, "Weapon_Damage", (5 * stage))
ds_map_replace(data, "Magic_Power", (10 * stage))
ds_map_replace(data, "Spells_Energy_Cost", (-6 * stage))
ds_map_replace(data, "Skills_Energy_Cost", (-6 * stage))
ds_map_replace(data, "MP", (8 * stage))
if (stage == 1)
    ds_map_replace(data, "Fatigue_Gain", 66)
if (stage == 2)
    ds_map_replace(data, "Fatigue_Gain", 33)
if (stage == 3)
    ds_map_replace(data, "Fatigue_Gain", -33)
if (stage == 4)
    ds_map_replace(data, "Fatigue_Gain", -66)
